
services:
  app:
    build: .
    container_name: spring_SistemasA3
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/A3_sistemas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mom3040#
    working_dir: /app
    entrypoint: ["java", "-jar", "app.jar"]
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: SistemasA3_db
    environment:
      MYSQL_ROOT_PASSWORD: Mom3040#
      MYSQL_DATABASE: A3_sistemas
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: