version: '3.8'
services:
  app:
    build: .
    container_name: spring_SistemasA3
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Mom3040#
    working_dir: /app
    entrypoint: ["java", "-jar", "app.jar"]
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: SistemasA3_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mom3040#
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: